### ISSUE TITLE
Order of Managed objects added to environment

### ISSUE THREAD

**Issue by hmashlah** [HubSpot/dropwizard-guice#34]
AutoConfig adds the managed object in random order since subclasses of Managed are returned as a Set.
The Managed objects are started by dropwizard in the order in which they were added to the environments and stopped in that reverse order.
As a solution I suggest supporting selective AutoConfig settings like:
GuiceBundle.<MqComConfig>newBuilder().enableAutoConfig().excludeManaged()
or split AutoConfig to be per AutoConfigManaged, AutoConfigHealthCheck .....

**Comment by nikhilp-flipkart** [comment]
Is there a way to control the ordering of managed objects ?

**Comment by jhaber** [comment]
Over time we have found AutoConfig does more harm than good. We have since released a new library that contains many design improvements (removing AutoConfig completely is one of them). I would suggest switching to that if you AutoConfig is causing problems:
https://github.com/HubSpot/dropwizard-guicier
